[package]
name = "simd-itertools"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "SIMD-accelerated alternatives for common operations like contains, max, find etc."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"


[[bench]]
name = "min"
harness = false

[profile.release]
debug = true
